"""unfollow

Revision ID: ef1caff1ce7f
Revises: 7d5c7096c446
Create Date: 2023-07-23 00:38:07.698670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1caff1ce7f'
down_revision = '7d5c7096c446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_mgmt.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user_mgmt.id'], )
    )
    # ### end Alembic commands ###
